// <auto-generated />
using System;
using EventPlanner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventPlanner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EventPlannerDbContext))]
    [Migration("20260521080002_AddDevelopmentSeedData")]
    partial class AddDevelopmentSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventPlanner.Domain.Entities.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("StartDateTime");

                    b.ToTable("calendar_events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c516b2a-7f1f-4c19-9a0d-09362d3d2fd1"),
                            Category = "Online",
                            Color = "#DC2626",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "An event for IT students and companies.",
                            EndDateTime = new DateTimeOffset(new DateTime(2026, 5, 20, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizerId = new Guid("8a5edca7-8f80-4ed6-8b91-01863782b51b"),
                            StartDateTime = new DateTimeOffset(new DateTime(2026, 5, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Tech Career Fair 2026",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("d8204401-a77d-44d4-ae96-98e31f59a580"),
                            Category = "Workshop",
                            Color = "#2563EB",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Roadmap discussion for the event platform.",
                            EndDateTime = new DateTimeOffset(new DateTime(2026, 5, 21, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizerId = new Guid("8a5edca7-8f80-4ed6-8b91-01863782b51b"),
                            StartDateTime = new DateTimeOffset(new DateTime(2026, 5, 21, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Product Planning",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("2d4487e7-8403-4454-b0f2-e5d5201e42e6"),
                            Category = "Workshop",
                            Color = "#7C3AED",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Hands-on session for building calendar interactions.",
                            EndDateTime = new DateTimeOffset(new DateTime(2026, 5, 22, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizerId = new Guid("a9cb5e4e-7777-4e5d-bef3-6d795663b246"),
                            StartDateTime = new DateTimeOffset(new DateTime(2026, 5, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Frontend Calendar Workshop",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("e5947a8d-4730-4210-8daa-90058b05fef2"),
                            Category = "InPerson",
                            Color = "#F97316",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Informal meetup for students, mentors, and organizers.",
                            EndDateTime = new DateTimeOffset(new DateTime(2026, 5, 22, 19, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizerId = new Guid("c7d731cc-7e02-4d89-9330-4210e4221ab5"),
                            StartDateTime = new DateTimeOffset(new DateTime(2026, 5, 22, 17, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Community Networking Evening",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("3dfc25b7-c221-40ef-afc3-a8795ee6513f"),
                            Category = "InPerson",
                            Color = "#059669",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Check rooms, signage, registration desk, and equipment.",
                            EndDateTime = new DateTimeOffset(new DateTime(2026, 5, 23, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizerId = new Guid("77ee5d58-ef01-449d-a418-936c19d0cfdf"),
                            StartDateTime = new DateTimeOffset(new DateTime(2026, 5, 23, 8, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Venue Walkthrough",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f29d4f5d-3972-4e41-b2a5-405137fb44dc"),
                            Category = "Online",
                            Color = "#0891B2",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Review sponsor booth needs and presentation materials.",
                            EndDateTime = new DateTimeOffset(new DateTime(2026, 5, 23, 13, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizerId = new Guid("8a5edca7-8f80-4ed6-8b91-01863782b51b"),
                            StartDateTime = new DateTimeOffset(new DateTime(2026, 5, 23, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Sponsor Check-in",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("57c4877d-b218-42e7-8040-c6f422f2641d"),
                            Category = "Hybrid",
                            Color = "#DB2777",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Panel with mentors joining both onsite and remotely.",
                            EndDateTime = new DateTimeOffset(new DateTime(2026, 5, 24, 12, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizerId = new Guid("c7d731cc-7e02-4d89-9330-4210e4221ab5"),
                            StartDateTime = new DateTimeOffset(new DateTime(2026, 5, 24, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Hybrid Mentorship Panel",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b605d60d-67c9-4497-b53a-e69f0d48c044"),
                            Category = "Conference",
                            Color = "#DC2626",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kickoff keynote for the event planner internship demo.",
                            EndDateTime = new DateTimeOffset(new DateTime(2026, 5, 25, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizerId = new Guid("8a5edca7-8f80-4ed6-8b91-01863782b51b"),
                            StartDateTime = new DateTimeOffset(new DateTime(2026, 5, 25, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Conference Opening Keynote",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("7dc6bdcb-463d-442d-a976-86a673e5cebf"),
                            Category = "Workshop",
                            Color = "#16A34A",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Prepare volunteers for registration and attendee support.",
                            EndDateTime = new DateTimeOffset(new DateTime(2026, 5, 25, 15, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizerId = new Guid("77ee5d58-ef01-449d-a418-936c19d0cfdf"),
                            StartDateTime = new DateTimeOffset(new DateTime(2026, 5, 25, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Volunteer Training",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("1d7ef292-5650-4534-a78c-f6076dd726be"),
                            Category = "Other",
                            Color = "#9333EA",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Review event branding, badges, and visual materials.",
                            EndDateTime = new DateTimeOffset(new DateTime(2026, 5, 26, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizerId = new Guid("a9cb5e4e-7777-4e5d-bef3-6d795663b246"),
                            StartDateTime = new DateTimeOffset(new DateTime(2026, 5, 26, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Design Review",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("7aefc1e5-9c7a-4df4-9d55-b7a5197d1b96"),
                            Category = "Online",
                            Color = "#0F172A",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Admin review of event readiness, risks, and next actions.",
                            EndDateTime = new DateTimeOffset(new DateTime(2026, 5, 27, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizerId = new Guid("f1a70547-12ce-4d4f-b5b1-a22cb6efdf5d"),
                            StartDateTime = new DateTimeOffset(new DateTime(2026, 5, 27, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Admin Operations Review",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5d487840-184d-4ce5-875a-56dadbe446a3"),
                            Category = "Hybrid",
                            Color = "#EA580C",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Collect lessons learned and improvement ideas.",
                            EndDateTime = new DateTimeOffset(new DateTime(2026, 5, 29, 16, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrganizerId = new Guid("8a5edca7-8f80-4ed6-8b91-01863782b51b"),
                            StartDateTime = new DateTimeOffset(new DateTime(2026, 5, 29, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Post-event Retrospective",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("EventPlanner.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a5edca7-8f80-4ed6-8b91-01863782b51b"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "organizer@example.com",
                            FirstName = "Demo",
                            IsActive = true,
                            LastName = "Organizer",
                            PasswordHash = "development-password-hash",
                            Phone = "+37360000000",
                            Role = "Organizer",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f1a70547-12ce-4d4f-b5b1-a22cb6efdf5d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@example.com",
                            FirstName = "Alex",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "development-password-hash",
                            Phone = "+37360000001",
                            Role = "Admin",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("c7d731cc-7e02-4d89-9330-4210e4221ab5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "mara.community@example.com",
                            FirstName = "Mara",
                            IsActive = true,
                            LastName = "Community",
                            PasswordHash = "development-password-hash",
                            Phone = "+37360000002",
                            Role = "Organizer",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a9cb5e4e-7777-4e5d-bef3-6d795663b246"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "victor.design@example.com",
                            FirstName = "Victor",
                            IsActive = true,
                            LastName = "Design",
                            PasswordHash = "development-password-hash",
                            Phone = "+37360000003",
                            Role = "Organizer",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("77ee5d58-ef01-449d-a418-936c19d0cfdf"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "nina.operations@example.com",
                            FirstName = "Nina",
                            IsActive = true,
                            LastName = "Operations",
                            PasswordHash = "development-password-hash",
                            Phone = "+37360000004",
                            Role = "Organizer",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("EventPlanner.Domain.Entities.CalendarEvent", b =>
                {
                    b.HasOne("EventPlanner.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
